config/routes.rb
Trupoly::Application.routes.draw do

  get "properties/index"

  get "admin/show"

  get "admin/new_prop"

  get "admin/new"

  match '/users/show/:id' => "users#show", :via => :get, :as => :show_user
  match '/properties/show/:id' => "properties#show", :via => :get, :as => :prop
  match '/admin/investment/:id', :to => 'admin#investment', :as => :investment
  post '/admin/invested', :to => 'admin#invest', :as => :invest

  root to: 'users#show'
  get   '/myaccount', :to => 'users#show', :as => :show
  get   '/settings', :to => 'users#settings', :as => :settings
  get   '/logout', :to => 'users#logout', :as => :logout

  get   '/login', :to => 'sessions#index', :as => :login
  post  '/login_post', :to => 'sessions#login', :as => :login_post
  get   '/new_user', :to => 'sessions#new', :as => :new_user
  post  '/create', :to => 'sessions#create', :as => :create

  post  '/admin/new', :to => 'admin#new', :as => :new_prop
  

end

app/models/investment.rb
class Investment < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
  attr_accessible :capital
  attr_accessible :user_id, :property_id
end

app/models/property.rb
class Property < ActiveRecord::Base
  attr_accessible :address, :available_value, :city, :client_irr, :country_code, :description, :irr, :purchase_value, :state
  has_many :investments
  accepts_nested_attributes_for :investments
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :user
  belongs_to :property
  attr_accessible :investment
  attr_accessible :user_id, :property_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :account_balance, :account_invested, :account_total, :email, :first_name, :last_name, :password
  has_many :investments
  accepts_nested_attributes_for :investments

  def IRR?
  	positions = Property.joins(:investments).where(:investments => {:user_id => self.id})
  	irr_sum = 0
  	cap_sum = 0
  	positions.each do |p|
  		p.investments.each do |q|
  			irr_sum = irr_sum + p.client_irr * q.capital
  			cap_sum = cap_sum + q.capital
  		end
  	end
  	if irr_sum == 0
  		return 0
  	end
  	return (irr_sum/cap_sum)
  rescue ActiveRecord::RecordNotFound
  	return 0
  end

  def is_admin?()
  	return self.email =~ /^(dhercher@colgate.edu|rsmith@colgate.edu)$/ 
  end

  def num_properties?
  	props = Property.joins(:investments).where(:investments => {:user_id => self.id})
  	num_props = 0
  	props.each do |p|
  		num_props = num_props + 1
  	end
  	return num_props
  rescue ActiveRecord::RecordNotFound
  	return 0
  end

end

app/controllers/admin_controller.rb
class AdminController < UsersController
  before_filter :require_admin

  def show
  	@users = User.order(:email)
  end

  def new_prop
  end

  def new
  	params[:property][:available_value] = params[:property][:purchase_value]
  	@property = Property.create!(params[:property])
  	@property = Property.where('lower(address) = lower(?) and lower(city) = lower(?) and lower(state) = lower(?) and lower(country_code) = lower(?)', params[:property][:address], params[:property][:city], params[:property][:state], params[:property][:country_code]).first_or_create(params[:property])
  	# @property = Property.where(:address => params[:property][:address], :city => params[:property][:city], :state => params[:property][:state], :country_code => params[:property][:country_code]).first_or_create(params[:property])
  	redirect_to proc {prop_url(@property.id)}
  end

  def investment
  	@user = params[:id]
  	@properties = Property.order(:city)
  end

  def invest
  	invest = Investment.where('user_id = ? and property_id = ?', params[:user_id], params[:property_id]).first_or_initialize(:capital => params[:property][:investment_value].to_f, :user_id => params[:user_id], :property_id => params[:property_id])
  	invest.user_id = params[:user_id].to_i
  	invest.property_id = params[:property_id].to_i
  	if invest.persisted?
  		invest.capital = invest.capital + params[:property][:investment_value].to_f
  	end
  	invest.save
  	user = User.find(params[:user_id])
  	user.account_total = user.account_total + params[:property][:investment_value].to_f
  	user.account_invested = user.account_invested + params[:property][:investment_value].to_f
  	user.save
  	# Just for continuity of records and sales?
  	investment = Purchase.first_or_initialize(:investment => params[:property][:investment_value].to_f, :user_id => params[:user_id], :property_id => params[:property_id])
  	investment.user_id = params[:user_id].to_i
  	investment.property_id = params[:property_id].to_i
  	investment.save

  	redirect_to proc {show_user_url(params[:user_id])}
  end

  private
  def require_admin
    unless User.find(session[:user_id]).is_admin?
      flash[:error] = "You must be logged in to access this section"
      redirect_to :login
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/properties_controller.rb
class PropertiesController < UsersController
  def show
  	id = params[:id]
    @property = Property.find(id)
  end

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
  	@style_sheets = 'sessions'
  end

  def login
  	user = User.where('email = ? and password = ?', params[:email], params[:password]).first!
  	session[:user_id] = user.id
  	redirect_to :root
  rescue ActiveRecord::RecordNotFound
  	flash[:notice] = "Wrong Email or Password"
  	redirect_to :login
  end

  def new
  	@style_sheets = 'sessions'
  end

  def create
  	params[:user][:account_balance] = 0
  	params[:user][:account_invested] = 0
  	params[:user][:account_total] = 0
  	user = User.where('lower(email) = lower(?)', params[:user][:email]).first_or_initialize(params[:user])
  	if user.new_record?
  		user.save
  		session[:user_id] = user.id
  		redirect_to :root
  	else
  		flash[:notice] = "Email already exists"
  		redirect_to :new_user
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :require_user

  def show
  	@style_sheets = 'users'
    if @admin
      @user = User.find(params[:id] || session[:user_id])
    else
  	  @user = User.find(session[:user_id])
    end

  rescue ActiveRecord::RecordNotFound
  	flash[:error] = "An Error Occurred, Please Login Again"
  	session[:user_id] = nil
  	redirect_to :login
  end

  def settings
  end

  def logout
  	session[:user_id] = nil
  	flash[:notice] = "Logout Successful"
  	redirect_to :login
  end

  private
  def require_user
    unless session[:user_id]
      flash[:error] = "You must be logged in to access this section"
      redirect_to :login and return
    end
    @admin = User.find(session[:user_id]).is_admin?
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/invest.html.haml
.container
  %h1 Attempted Investment

app/views/admin/investment.html.haml
.container
  %h1 Invest in a Property
  = form_tag invest_path do
    = label :property, :property_id, 'Choose Property'
    = select_tag "property_id", options_from_collection_for_select(@properties, "id", "description")
    = label :property, :investment_value, '**Investment Value** '
    = number_field :property, :investment_value, :in => 0...100000000, :step => 0.01
    %br
    = hidden_field_tag :user_id, @user
    = submit_tag 'Submit'

app/views/admin/new.html.haml
.container
  %h1 Loaded New Property

app/views/admin/new_prop.html.haml
.container
  %h1 Load New Property
  = form_tag new_prop_path do
    = label :property, :address, 'Address'  
    = text_field :property, 'address'
    = label :property, :city, "City"
    = text_field :property, 'city'
    = label :property, :state, "State"
    = text_field :property, 'state'
    = label :property, :country_code, "Country Code"
    = text_field :property, 'country_code' 
    %br
    = label :property, :irr, '**IRR**'
    = number_field :property, :irr, :in => 0...100, :step => 0.01
    = label :property, :client_irr, 'Client IRR'
    = number_field :property, :client_irr, :in => 0...100, :step => 0.01
    = label :property, :purchase_value, '**Purchase Value** '
    = number_field :property, :purchase_value, :in => 0...100000000, :step => 0.01
    %br
    = label :property, :description, "Description"
    = text_field :property, 'description' 
    %br
    = submit_tag "Submit" 

/ :address, :available_value, :city, :client_irr, :country_code, :description, :irr, :purchase_value, :state

app/views/admin/show.html.haml
.container
  %h1 User Accounts
  %table#users
    %thead
      %tr
        %th=link_to 'Email', admin_show_path(:sort => 'email'), :id => 'email_header'
        %th=link_to 'First Name', admin_show_path(:sort => 'first_name'), :id => 'first_name_header'
        %th=link_to 'Last Name', admin_show_path(:sort => 'last_name'), :id => 'last_name_header'
        %th=link_to 'Account Total', admin_show_path(:sort => 'account_total'), :id => 'account_total_header'
        %th=link_to 'Account Invested', admin_show_path(:sort => 'account_invested'), :id => 'account_invested_header'
        %th=link_to 'Account Balance', admin_show_path(:sort => 'account_balance'), :id => 'account_balance_header'
    %tbody
      - @users.each do |ex|
        %tr
          %td= link_to ex.email, "/users/show/#{ex.id}"
          %td= ex.first_name
          %td= ex.last_name
          %td= ex.account_total
          %td= ex.account_invested
          %td= ex.account_balance
          %td= link_to "invest", "/admin/investment/#{ex.id}" 
  %h2
    =  link_to 'Add New Property', admin_new_prop_path  

app/views/layouts/_footer.html.haml
.footer
  Trupoly Inc

app/views/layouts/_header.html.haml
= link_to root_path do
  .header1
    = image_tag 'trupoly.png', width: 250 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Trupoly
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      = content_tag :div, msg, :id => "flash_#{name}"
  .bg_photo= image_tag 'street_view.jpg', width: '200%' 
  %body
    - if @style_sheets != 'sessions'
      = button_to 'LOGOUT', '/logout', class:'button logout_button', :method => :get
    - if @admin
      = button_to 'ADMIN', '/admin/show', class:'button admin_button', :method => :get
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/properties/index.html.haml
%h1 Properties#index
%p Find me in app/views/properties/index.html.haml

app/views/properties/show.html.haml
.container
  %h1 Property Description
  %span.address= @property.address
  %span.city= @property.city
  %span.state= @property.state
  %span.country_code= @property.country_code
  %br
  Purchase Value:  $
  %span.purchase_value= @property.purchase_value
  %br
  Available Value:  $
  %span.available_value= @property.available_value
  %br
  IRR
  %span.irr= @property.client_irr
  \%

app/views/users/logout.html.haml
%h1 Logged Out
%p See Ya

app/views/users/settings.html.haml
%h1 Users#settings
%p Find me in app/views/users/settings.html.haml

app/views/users/show.html.haml
.container1
  %h1 My Trupoly Summary

.irr_container
  %h2 
  IRR
  =@user.IRR?

.account_total_container
  %h3 
  Account Total $
  =@user.account_total

.rent_rec_container
  %h4 
  Rent Received $
  =@user.account_balance

.account_stats_container
  %h5
  Value:
  =@user.account_invested
  %br
  Properties:
  =@user.num_properties?
  %br
  Available for Withdrawl
  =@user.account_balance


%h6
= link_to 'Sign Out', :logout